
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  version_build_number:
    name: Create version build number and push it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'

      - name: ggg
        uses: mikefarah/yq@master
        with:
          cmd: yq w pubspec.yaml '.version' "$(cut -d'+' -f1 <<<"${{ steps.yq.outputs.result }}")"+${{ github.run_number }}
      - name: Update pubspec.yaml version
        uses: test-room-7/action-update-file@v1
        with:
          file-path: pubspec.yaml
          commit-msg: auto update pubspec.yaml version
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}